server:
  error:
    include-exception: true
    include-stacktrace: on_param
  port: 18080
  servlet:
    context-path: /certmgr

cert-mgr:
  openssl-path: "C:/Windows/System32/OpenSSH/ssh.exe"
  data-dir: ./data
  log-dir: ./log

# springMacroRequestContext.model._csrf.parameterName
# _csrf.parameterName
spring:
  mustache:
    expose-request-attributes: true

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
    com:
      ezoneproject:
        certmgr: DEBUG
